server:
  port: 9000
spring:
  profiles:
    active: qa
  application:
    name: cards
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8071/}"
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      rabbit:
        bindings:
          springCloudBusInput:
            consumer:
              anonymousGroupPrefix: "${spring.application.name}-service-${spring.profiles.active:default}-"

management:
  endpoints:
    web:
      exposure:
        # enable all actuator end-points
        include: "*"
