spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    show-sql: true




build:
  version: "1.0"


accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345