spring:
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
        trace: false
  jpa:
    show-sql: false




build:
  version: "1.0"


accounts:
  message: "Welcome to EazyBank accounts related local docker APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
