spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    show-sql: true



build:
  version: "1.0"


loans:
  message: "Welcome to EazyBank loans related PROD APIs "
  contactDetails:
    name: "product owner John Doe - Product Owner"
    email: "owner@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345