server:
  port: 8090

spring:
  web:
    resources:
      add-mappings: false
  profiles:
    active: default
  application:
    name: loans
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8071/}"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      rabbit:
        bindings:
          springCloudBusInput:
            consumer:
              anonymousGroupPrefix: "${spring.application.name}-service-${spring.profiles.active:default}-"


eureka:
  instance:
    # the default is thet the server should register itself using DNS but in local we relay on ip and port
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    # eureka server URL
    service-url:
      # must be (camelCase)
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8070/eureka/}

# enable detailed information to be shown in eureka dashboard, get fetch through actuator info end-point
info:
  app:
    name: loans
    description: "Eazy Bank Loans Application"
    version: "1.0.0"

management:
  endpoints:
    web:
      exposure:
        # enable all actuator end-points
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  # enable info end-point
  info:
    env:
      enabled: true


endpoints:
  shoutdown:
    enabled: true