server:
  port: 8090

spring:
  profiles:
    active: qa
  application:
    name: loans
  config:
    import: "optional:configserver:http://localhost:8071/"
  datasource:
    url: jdbc:h2:mem:loandb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
