server:
  port: 8080
spring:
  profiles:
    active: prod
  application:
    name: accounts
  config:
    import: "optional:configserver:http://localhost:8071/"
  datasource:
    url: jdbc:h2:mem:accountdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      rabbit:
        bindings:
          springCloudBusInput:
            consumer:
              anonymousGroupPrefix: "${spring.application.name}-service-${spring.profiles.active:default}-"

management:
  endpoints:
    web:
      exposure:
        # enable all actuator end-points
        include: "*"
