server:
  port: 8071

spring:
  application:
    name: configserver
  profiles:
    #        only for loading config files classpath and system file approaches
    #active: native
    active: git
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      rabbit:
        bindings:
          springCloudBusInput:
            consumer:
              anonymousGroupPrefix: "${spring.application.name}-service-${spring.profiles.active:default}-"
    config:
      server:
        # reading the files from git repo and branch
        git:
          uri: "https://github.com/Esmaeeilenani/eazy-bytes-master-spring-microservices-course.git"
          # branch name
          default-label: config-files
          timeout: 5
          # clone the repo once the server is up (do not wait  intel the first request hits)
          clone-on-start: true
          # always re-pull changes for updates
          force-pull: true
#        only for loading config files classpath and system file approaches
#        native:
#          search-locations: "classpath:/config"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true


encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"
