server:
  port: 9010

spring:
  application:
    name: message
  cloud:
    function:
      definition: email|sms
    stream:
      bindings:
        # should be same as function definition
        emailsms-in-0:
          destination: send-communication
          group: ${spring.application.name}
        emailsms-out-0:
          destination: communication-sent
      kafka:
        binder:
          brokers: ${KAFKA_URL:localhost:9092}
          autoCreateTopics: true

# this for rabbit MQ integrations
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    connection-timeout: 10s