apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-deployment
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: esmaeeil/accounts:2.0
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: ACCOUNTS_APPLICATION_NAME
            - name: EUREKA_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: EUREKA_SERVER_URL
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: SPRING_RABBITMQ_HOST



          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: accounts
spec:
  selector:
    app: accounts
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080